# Generated by Django 3.2.2 on 2021-05-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_thread_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='unread_count',
            field=models.IntegerField(null=True),
        ),
    ]
